version: 2.1

commands:
  build_cpp:
    description: "Install dependencies (C++) and build toppra C++ API"
    steps:
      - run:
          name: dependencies
          command: |
            sudo apt install -y curl
            echo "deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -sc) robotpkg" \
              | sudo tee /etc/apt/sources.list.d/robotpkg.list
            curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key \
              | sudo apt-key add -
            sudo apt update
            sudo apt install -y clang-tidy libeigen3-dev robotpkg-pinocchio robotpkg-qpoases libglpk-dev
            git clone https://github.com/pybind/pybind11
            cd pybind11 && git checkout v2.5.0
            mkdir build && cd build && cmake -DPYBIND11_TEST=false .. && sudo make install

            git clone https://github.com/msgpack/msgpack-c.git
            cd msgpack-c && git checkout cpp-3.2.1 && cmake -DMSGPACK_CXX11=ON -DMSGPACK_BUILD_EXAMPLES=OFF -DMSGPACK_CXX_ONLY=ON .
            sudo make install
            
          working_directory: ~/
      - run:
          name: build
          command: |
            export LD_LIBRARY_PATH=/opt/openrobots/lib:${LD_LIBRARY_PATH}
            export CMAKE_PREFIX_PATH=/opt/openrobots
            mkdir build && cd build && cmake -DBUILD_WITH_PINOCCHIO=ON -DBUILD_WITH_qpOASES=ON -DBUILD_WITH_GLPK=ON -DPYTHON_BINDINGS=ON -DPYBIND11_PYTHON_VERSION=3.7 -DOPT_MSGPACK=ON ..
            make -j4
          working_directory: ~/repo/cpp

  install_python:
    description: "Install Python dependencies and toppra Python API"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies3-{{ checksum "requirements3.txt" }}

      - run:
          name: install dependencies
          command: |
            virtualenv --python python3.7 venv3 && . venv3/bin/activate
            pip install numpy cython
            invoke install-solvers
            pip install -e .[dev]

      - save_cache:
          paths:
            - ./venv3
          key: v1-dependencies3-{{ checksum "requirements3.txt" }}

jobs:
  # Test the base python installation on multiple environment.
  python:
    parameters:
      python-version:
        type: string
    docker:
      - image: hungpham2511/toppra-dep:0.0.3

    working_directory: ~/repo
    steps:
      - checkout
      # - install_python
      - run:
          name: Run tests for python << parameters.python-version >>
          command: |
            virtualenv --python python3.7 venv3 && . venv3/bin/activate
            pip install tox numpy cython  # need numpy and cython to create the sdist
            tox -e py<< parameters.python-version >>

      - store_artifacts:
          path: test-reports
          destination: test-reports

  # Test the cpp api and bindings on python3.7
  cpp-python37:
    docker:
      - image: hungpham2511/toppra-dep:0.0.3

    working_directory: ~/repo

    steps:
      - checkout
      - build_cpp
      - run:
          name: test (C++)
          command: |
            ./tests/all_tests
          working_directory: ~/repo/cpp/build
      - run:
          name: codestyle (C++)
          command: |
            clang-tidy  src/**/*.cpp \
            -checks=clang-analyzer-*,clang-analyzer-cplusplus*,cppcoreguidelines-*,performance-*,modernize-*,readability-,-cppcoreguidelines-pro-bounds-array-to-pointer-decay\
            -warnings-as-errors=clang-analyzer-*,clang-analyzer-cplusplus*,cppcoreguidelines-*,modernize-*
          working_directory: ~/repo/cpp
      - install_python
      - run:
          name: test (Python)
          command: |
            . venv3/bin/activate
            mkdir test-reports
            python --version
            python -m pytest -q tests --durations=3 --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

  pre-release:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Pull all known tags and check that the tag in VERSION has not already exist.
          command: |
            VERSION=`cat VERSION`
            git fetch --tags
            git tag $VERSION

  release:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Tag code with the latest version in VERSION and push tag.
          command: |
            VERSION=`cat VERSION`
            git fetch --tags
            git tag $VERSION
            git push origin $VERSION
      - run:
          name: Publish to PyPI
          command: |
            echo "TODO"

workflows:
  version: 2
  integrate:
    jobs:
      - python:
          matrix:
            parameters:
              python-version: ["27", "36", "37"]
      - cpp-python37

  release:
    jobs:
      - pre-release:
          filters:
            branches:
              only:
              - fix-ci
              - /release-.*/

  publish:
    jobs:
      - release:
          filters:
            branches:
              only:
              - master



