version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /feat-*/
        - circleci
    docker:
      - image: hungpham2511/toppra-dep:0.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements3.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv toppra-venv
            . toppra-venv/bin/activate
            pip install -q -r requirements3.txt

      - save_cache:
          paths:
            - ./toppra-venv
          key: v1-dependencies-{{ checksum "requirements3.txt" }}

      # build install
      - run:
          name: build and install
          command: |
            . toppra-venv/bin/activate
            python setup.py develop

      - run:
          name: test
          command: |
            . toppra-venv/bin/activate
            pytest -xv

      - store_artifacts:
          path: test-reports
          destination: test-reports
