# This is a basic workflow to help you get started with Actions

name: lint (C++)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dep
      run: |
        sudo apt-get install -y clang-tidy libeigen3-dev

    # Runs a set of commands using the runners shell
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/cpp && mkdir build && cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..

    - name: lint
      run: |
        clang-tidy  ../src/**/*.cpp -checks="clang-analyzer-*,clang-analyzer-cplusplus*,cppcoreguidelines-*,performance-*,modernize-*"

        
