name: Lint (C++, clang-tidy)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt install -y curl
        echo "deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -sc) robotpkg" \
          | sudo tee /etc/apt/sources.list.d/robotpkg.list
        curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key \
          | sudo apt-key add -
        sudo apt update
        sudo apt install -y clang-tidy libeigen3-dev robotpkg-pinocchio robotpkg-qpoases

    - name: Lint
      run: |
        cd $GITHUB_WORKSPACE/cpp
        export LD_LIBRARY_PATH=/opt/openrobots/lib:${LD_LIBRARY_PATH}
        export CMAKE_PREFIX_PATH=/opt/openrobots
        mkdir build && cd build && cmake -DBUILD_WITH_PINOCCHIO=ON -DBUILD_WITH_qpOASES=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
        clang-tidy  src/**/*.cpp \
          -checks=clang-analyzer-*,clang-analyzer-cplusplus*,cppcoreguidelines-*,performance-*,modernize-*,readability-,-cppcoreguidelines-pro-bounds-array-to-pointer-decay\
          -warnings-as-errors=clang-analyzer-*,clang-analyzer-cplusplus*,cppcoreguidelines-*,modernize-*
